### ISSUE TITLE
Catching up?

### ISSUE THREAD

**Issue by suntong** [bramp/antlr4-grammars#7]
This repo has been stop updating since nearly two years ago. Any plan for catching up?

The https://github.com/antlr/grammars-v4 was last updated _"22 hours ago"_ as we speak.

**Comment by suntong** [comment]
Check out https://github.com/go-sqlparser/antlr4-grammars that has latest updated.

**Comment by bramp** [comment]
Sorry, finally updated everything.

Happy to receive pull requests for keeping this repo up to date.
